# Generated by Django 4.1 on 2022-10-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=25, null=True)),
                ('name', models.CharField(max_length=40)),
                ('release_date', models.DateField(blank=True)),
                ('number_of_stars', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('instrument', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('genre_choice', models.CharField(choices=[('RAP', 'RAP'), ('H-H', 'HIPHOP'), ('CM', 'CLASSICAL-MUSIC'), ('POP', 'POP'), ('HR', 'HARD-ROCK')], max_length=3)),
            ],
        ),
    ]
